version: "3"

services:
  proxy-server:
    container_name: proxy-server
    build:
      context: .
    ports:
      - "7009:7777"
    entrypoint: yarn start
    restart: always
    networks: 
      - proxy
networks:
  proxy:
    driver: bridge